# Generated by Django 2.1.7 on 2019-03-23 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=240)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('max_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('path_png', models.CharField(max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Profile')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Skin')),
            ],
        ),
        migrations.AddField(
            model_name='skin',
            name='profile',
            field=models.ManyToManyField(through='game.UserSkins', to='game.Profile'),
        ),
    ]
