# Generated by Django 2.1.7 on 2019-03-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_skin',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='skin',
            name='slang',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
