# Generated by Django 2.1.7 on 2019-03-23 07:06

from django.db import models, migrations


def load(apps, schema_editor):
    Skin = apps.get_model("game", "Skin")
    Skin.objects.create(slang="default",path_png="base.png")
    Skin.objects.create(slang="azores",path_png="azoresFlag.png")
    Skin.objects.create(slang="black",path_png="blackSkin.png")
    Skin.objects.create(slang="blue",path_png="blueSkin.png")
    Skin.objects.create(slang="camoes",path_png="camoesSkin.png")
    Skin.objects.create(slang="green",path_png="greenSkin.png")
    Skin.objects.create(slang="lil",path_png="lilSkin.png")
    Skin.objects.create(slang="pink",path_png="pinkSkin.png")
    Skin.objects.create(slang="portugal",path_png="portugalSkin.png")
    Skin.objects.create(slang="red",path_png="redSkin.png")
    Skin.objects.create(slang="skyrim",path_png="skyrimSkin.png")
    Skin.objects.create(slang="spongebob",path_png="spongeBobSkin.png")
    Skin.objects.create(slang="t_body",path_png="tSkin.png")
    Skin.objects.create(slang="yellow",path_png="yellowSkin.png")


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0005_auto_20190323_0811'),
    ]

    operations = [
        migrations.RunPython(load)
    ]
